.github/workflows/Build.yml, .github/workflows/Deploy.yml, .github/workflows/pr-build.yml, README.md, src/app.test.ts
=> Adding CI/CD Actions

.env.sample, app.json, ormconfig.json, src/app.ts
Add postgres as an addon of heroku and use `DATABASE_URL` as the env variable
=> Add postgres addon to heroku app.json

README.md
Tweaking some high level README details
=> Cleaning up the README

src/migration/1573329583500-CreateTeamSyncHash.ts
Fixing migrations to include `team.syncHash`
=> Fixing table migrations to include team.syncHash

.github/CODEOWNERS, package-lock.json, src/tests/judging.test.ts
=> Remove flatmap

package-lock.json, package.json, src/api/index.ts, src/entities/judge.ts, src/pages/_document.tsx, src/pages/judge/[secret].tsx, src/tests/judging.test.ts
=> Judging UI

src/pages/judge/[secret].tsx
=> Add table number

src/api/index.ts, src/entities/judge.ts, src/pages/judge/[secret].tsx
=> Add skip functionality

.github/workflows/Build.yml, .github/workflows/PR-Build.yml, README.md, jest.config.js, package.json
Adding Codecov to the project
Fixes #31
=> Adding Codecov

.github/labeler.yml, .github/workflows/PRLabel.yml, src/entities/judge.ts
Adds a new labeler action that triggers on PR creation to make sure appropriate labels are applied to each PR
Fixes #19
=> Adding a new action to label PRs with appropriate labels

README.md
=> Fixing broken README link

.github/workflows/Build.yml, .github/workflows/PR-Build.yml
Adding an action to cache dependencies
Fixed #28
=> GitHub Actions Caching

README.md, src/pages/judge/[secret].tsx
Added LGTM to the README and fixed a problem it found
=> Lgtm integration

README.md
Added the code quality badge to the README
=> Add code quality badge to README

src/migration/1574797652947-AddPreviousTeamColumn.ts
Removed the duplicate syncHash migration
=> Fix syncHash migration

.github/workflows/Build.yml, .github/workflows/Test.yml
Refactoring actions to make them more granular
Fixes #54
=> Refactoring Actions

package-lock.json
Updating our dependencies to mitigate vulnerabilities
=> Fixing dependency vulnerabilities

.github/workflows/Test.yml
Fixing an issue that could be preventing Tests from registering as a status check for PRs
=> Fixing ordering for Action patterns

package-lock.json
Update `serialize-javascript` using `npm audit`
=> Fix security vulnurability

.github/workflows/PR-Build.yml, .github/workflows/Test.yml
Renaming the test job to allow it to be unique
=> Clearing up required status checks

.eslintrc.js, package-lock.json, package.json, src/pages/_document.tsx, src/pages/judge/[secret].tsx
Added the react linting rules to eslint and then fixed the issues it had
=> Add React linter and fix errors

src/slack/actions/registerTeam.ts
Fixed an issue where the app would throw when no team members were specified from mobile while registering a team
Fixes #81
=> Fixing an issue preventing mobile users from registering their team

src/api/judging.ts, src/app.ts, src/entities/judgingVote.ts, src/index.ts, src/slack/actions/subscribe.ts, src/slack/actions/supportRequest.ts, src/slack/actions/unsubscribe.ts, src/slack/blocks/dashboardBlocks.ts, src/slack/index.ts, src/slack/utilities/messageUsers.ts, src/tests/api/judging.test.ts, src/tests/app.test.ts, src/tests/entities/config.test.ts, src/tests/entities/judging.test.ts, src/tests/entities/supportRequest.test.ts, src/tests/entities/team.test.ts, src/tests/judging.test.ts, src/tests/testdb.test.ts, src/tests/testdb.ts, src/tests/utilities.ts
- Updating scoring to return an actual score instead of an average position
- Updating scoring to include the option for a bonus score
- Closes #87
=> Updating judging to return an actual score

src/api/admin.ts, src/app.ts
=> Bolt doesn't like preformatted json

.eslintrc.js, src/api/supportRequest.ts, src/pages/index.tsx, src/tests/api/supportRequest.test.ts
Added the no show button and it now shows recent pop when you get next in queue
=> Show recent pop and add no show button

src/api/index.ts
Fixing an issue that caused skip to not function
- Fixes #83
=> Fixing an issue where skip wasn't working properly

src/slack/actions/supportRequest.ts
Fixing an issue where the wrong support queue type was displayed in admin notifications.
- Fixes #99
=> Support Queue Notification Fix

Authors.md, package-lock.json, src/pages/index.tsx
- Changes layout of help request queue items to cards instead of a table.
- Queue layout is now more mobile-friendly.
None
=> Updating the help queue layout to cards instead of a table

package-lock.json, src/api/supportRequest.ts, src/pages/index.tsx, src/pages/login.tsx
Added admin name so when we move someone to in progress we tell them who to come to see
=> Add admin name

src/api/judging.ts, src/pages/index.tsx, src/tests/api/judging.test.ts
=> Judge results

app.json
Adding `JUDGE_SECRET` to the Heroku config
Fixes #110
=> Adding JUDGE_SECRET to Heroku config

src/slack/actions/supportRequest.ts
Adding a request to get the real username when someone joins the support queue
=> Adding a request to get the real username when someone joins the support queue

src/slack/actions/registerTeam.ts, src/slack/blocks/dashboardBlocks.ts
=> Showing team registration button 24/7

package-lock.json, package.json
Updating project dependencies, making `@types/react` a main dependency to make Next.js happy
=> Bumping project dependencies, fixing an issue with a next dependency

src/slack/README.md
=> Slack permission scope update

src/slack/README.md
Added the `mpim:write` scope to the Slack setup file
=> Add mpim:write scope to Slack setup

.github/PULL_REQUEST_TEMPLATE.md
Changed the links for the PR template (made the same changes in here, so click those links above to see the changes ☝️ )
Fixes #137
=> Update Authors.md link

.env.sample, Authors.md, README.md
After discussing with Spencer for a bit, Smit and I decided to add a little bit more clarification to the Readme in order to make it a bit easier to follow (Specifically in the "Local Development" section). If there's anything wrong with what we've added (typos, grammar, etc.), please let us know and we'll get on it as soon as we can!
=> Simple Edit to the Readme

src/app.ts
=> Test next fix

README.md
Editing postgres docs to include better installation instructions as well as suggestions for how to view/edit the data.
=> Updating Postgres docs

.github/PULL_REQUEST_TEMPLATE.md
This updates the PR template to make things clearer to contributors
Closes #155
=> Fixing the PR template file

src/slack/README.md
Fixing docs to mention home tab enablement
=> Updating docs with Home Tab instructions

src/slack/README.md
=> Fixing a typo in the README

src/slack/README.md
Adding a reference to the `app_home_opened` event
=> Updating Slack docs to include the app_home_opened event

src/api/config.ts, src/entities/config.ts, src/pages/index.tsx
Co-Authored-By: Dhruv Tailor <11343998+TheDivexz@users.noreply.github.com>
Co-Authored-By: Joseph Nalepka <70769982+Peruggia29@users.noreply.github.com>
added the button
added the function to handletoogle
closes #204
=> UI component for editing config items

src/discord/events/message/help.ts, src/discord/events/message/index.ts, src/tests/discord/events/message/help.test.ts
Remove items from help that should be hidden (like ping)
=> Add hidden help items

README.md
Fixing a broken link in the README
=> Fixing the feature request link

src/tests/app.test.ts
Fixing an issue where pc tests failed when env changes were made via test files
=> Fixing an issue where tests fail on PC

.env.sample, src/app.ts, src/index.ts
Modifying the db connection process to check for a new environment variable which overrides SSL validation if needed (primarily for use in Heroku)
=> Improving the DB connection process

src/api/supportRequest.ts, src/components/RegisteredTeamsList.tsx, src/components/SupportQueue/SupportQueueItem.tsx, src/components/SupportQueue/index.tsx, src/entities/supportRequest.ts, src/migration/1611869663899-AddSupportRequestSupportName.ts, src/pages/support/[secret].tsx, src/tests/entities/supportRequest.test.ts
=> Highlighting the user's cards

.github/workflows/Build.yml
Fixing the health check process within our deploy action to actually use the healthcheck endpoint and fail if the build fails
Removing references to the TAMUHack branch
=> Fixing deploy action health check, removing TAMU references

src/index.ts
Changed the listening message to `Listening at http://localhost:3000/` so you can easily click to visit the page
=> Better listening message

Authors.md, src/IStringDictionary.ts, src/StringDictionary.ts, src/discord/events/message/exit.ts, src/discord/events/message/help.ts, src/discord/events/message/index.ts, src/discord/events/message/registerTeam.ts, src/discord/events/message/supportRequest.ts
Implements string dictionary for Discord event message
scoring calculation test failing
Closes #234 - String dictionary update
`Co-authored-by: Yun Phelps <36348871+YunPhelps@users.noreply.github.com>`
=> Implements string dictionary for Discord event message

jest.config.js
Reduce test coverage thresholds to accommodate removal of testdb tests.
=> Update coverage thresholds

src/app.ts
Added cookie-parser in app.ts
Closes #339 - A bug that creates a UnhandledPromiseRejectionWarning when the user enters their adminSecret stored in the database on the login page
=> added cookie-parser in app.ts

src/entities/team.ts, src/tests/entities/judging.test.ts, src/tests/entities/team.test.ts
Updated `team.test.ts` to mock database functions. Need some feedback since we are not sure if we went in the right direction. 
Related to #231 
`Co-authored-by: Evelio Ramos <44717805+eveliososa@users.noreply.github.com>`
=> Updated Tests for Team to Mock Database.

.eslintrc.js, src/api/admin.ts, src/api/config.ts, src/api/middleware/requireAuth.ts, src/app.ts, src/entities/config.ts, src/index.ts, src/pages/judge/[secret].tsx, src/tests/api/config.test.ts, src/tests/api/middleware/requireAuth.test.ts, src/tests/entities/config.test.ts, src/types/config.ts
Fixing config to avoid using strings to reference config items
=> Fixing config

src/entities/config.ts, src/tests/entities/config.test.ts
- Added better handling for unknown keys
- Fixing config issues and test coverage
Fixing issues with config retrieval and fixing tests
=> Fixing config bug and increasing test coverage

package-lock.json, package.json, src/api/config.ts, src/api/middleware/requireAuth.ts, src/app.ts, src/components/ConfigItem.tsx, src/entities/config.ts, src/pages/setup.tsx, src/tests/api/middleware/requireAuth.test.ts
Merged PR for issues 330, 331 and 332. Made changes to the requreAuth.ts from Tristen's PR: https://github.com/AmericanAirlines/Hangar/pull/360
Closes #332 - Config setup API
Closes #331 - Create setup Page
Closes #330 - Allow user to start app without adminSecret or discord/slack ready
Co-authored by: Tatum Hutton 78566681+tatumwashere@users.noreply.github.com
Co-authored by: Tristen Even 46259649+tristengeven@users.noreply.github.com
=> 332 config setup api

packages/api/.env.sample
Adding missing field to the default env file
=> Adding `SESSION_SECRET` to the default env file

packages/api/.eslintrc, packages/api/src/@types/index.d.ts, packages/api/src/api/auth/index.ts, packages/api/src/api/index.ts, packages/api/src/middleware/populateUser.ts, packages/api/tests/middleware/populateUser.test.ts, packages/api/tests/testUtils/testHandler.ts
Can be used to fetch the user entity and handle any errors relating to that
=> Add populateUser middleware

packages/api/src/entities/QueueUser.ts, packages/api/src/migrations/0007-add-assignee-to-queueuser-table.ts
Adds an `assignee` field to the `QueueUser` entity
Necessary for #431
=> QueueUser Assignee

.github/workflows/release.yaml, packages/api/.env.sample, packages/api/src/logger.ts, packages/api/src/orm.config.ts
Added release action to push to heroku
=> Heroku deployment action

packages/web/src/pages/app/index.tsx
Modifying the header text for registration
=> Verbiage tweaks

.github/workflows/release.yaml, packages/web/src/components/NavBar/NavBar.tsx, packages/web/src/pages/app/help.tsx, packages/web/src/pages/app/index.tsx, packages/web/tests/pages/app/help.test.tsx
- Navbar mobile and help page
- Deploy this branch
- Mobile navbar
- Test coverage
=> Mobile and queue place holder

packages/api/src/entities/Project.ts, packages/api/src/migrations/0009-make-table-number-unique.ts, packages/web/src/components/RegistrationModal/RegistrationForm.tsx, packages/web/tests/components/RegistrationModal/RegistrationForm.test.tsx
=> Fix table number bug

Authors.md, README.md
Changed the ReadMe file.
- Updated the Verbiage and steps
- Added User scopes and replaced the yaml file for creating slack app
Added my name/email to the Author.md File
Some of the Steps in the ReadMe file weren't described the best way so updated that
Scopes weren't present in Yaml file for the "create slack app".
=> feat: updating Slack docs

.eslintrc, .github/workflows/build.yml, .github/workflows/quality.yaml, .github/workflows/tests.yaml, hangar.code-workspace, packages/web/src/components/ErrorPageContent/ErrorPageContent.tsx, packages/web/src/components/ErrorPageContent/catGifs.ts, packages/web/src/theme/components.ts
=> feat: reducing max line length to 100, removing stale plugin recommendation, fixing workflow triggers

packages/api/src/api/auth/callback/slack/get.ts, packages/api/src/api/auth/get.ts, packages/api/src/api/auth/index.ts, packages/api/tests/api/auth/callback/get.test.ts, packages/api/tests/api/auth/get.test.ts, packages/api/tests/api/auth/index.test.ts, packages/web/src/pages/index.tsx
=> feat: fix a few messed up endpoints

packages/api/tests/setupTests.ts, packages/api/tests/testUtils/mockEnv.test.ts, packages/api/tests/testUtils/mockEnv.ts, packages/api/tests/utils/database.test.ts
Adding a new test util method to easily mock the environment on a per-test basis
=> feat: implementing mockEnv util

packages/api/src/api/auth/callback/slack/get.ts, packages/api/src/api/auth/callback/slack/index.ts, packages/api/src/api/auth/callback/slack/utils/localRedirect.ts, packages/api/src/api/index.ts, packages/api/src/api/users/index.ts, packages/api/src/api/users/post.ts, packages/api/src/utils/authenticateUser.ts, packages/api/tests/api/auth/callback/slack/get.test.ts, packages/api/tests/api/auth/callback/slack/index.test.ts, packages/api/tests/api/auth/callback/slack/utils/localRedirect.test.ts, packages/api/tests/api/index.test.ts, packages/api/tests/api/users.ts/index.test.ts, packages/api/tests/api/users.ts/post.test.ts, packages/api/tests/setupTests.ts, packages/api/tests/utils/authenticateUser.test.ts, packages/database/src/entities/JudgingVote.ts, packages/web/src/components/layout/AppLayout/AppLayout.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavBar.tsx, packages/web/src/pages/error.tsx, packages/web/src/theme/index.ts, yarn.lock
- Fixing issues related to auth
- Improving error page
- Updating yarn.lock
- Updating theme
- Updating nav
=> fix: fixing issues related to auth

packages/api/src/api/users/index.ts, packages/api/src/middleware/sessionMiddleware.ts, packages/api/tests/api/auth/callback/slack/index.test.ts, packages/api/tests/api/auth/index.test.ts, packages/api/tests/api/health/index.test.ts, packages/api/tests/api/index.test.ts, packages/api/tests/api/users.ts/index.test.ts, packages/api/tests/middleware/sessionMiddleware.test.ts, packages/api/tests/testUtils/createMockNext.ts
=> feat: refactoring session middleware, refactoring test utils

packages/api/src/api/users/index.ts, packages/api/src/middleware/userMiddleware.ts, packages/api/src/middleware/validateSessionMiddleware.ts, packages/api/tests/api/users.ts/index.test.ts, packages/api/tests/middleware/mockData.ts, packages/api/tests/middleware/userMiddleware.test.ts, packages/api/tests/middleware/validateSessionMiddleware.test.ts
=> feat: isolate middlewares

packages/api/package.json, packages/api/src/api/users/put.ts, packages/api/src/utils/validatePayload.ts, packages/api/tests/api/users/put.test.ts, packages/api/tests/utils/validatePayload.test.ts, packages/shared/package.json, packages/shared/src/index.ts, packages/shared/src/schema/index.ts, packages/shared/src/schema/users/index.ts, packages/shared/src/schema/users/put.ts, packages/shared/tests/schema/users/put.test.ts, yarn.lock
Adding a new validator util to help with quick and consistent API validation
=> feat: API Validator

packages/database/src/entities/Judge.ts, packages/database/src/migrations/.snapshot-hangar.json, packages/database/src/migrations/0002-add-unique-index-to-judge-user.ts
Adding a missing `ref` property to the annotation for `Judge.user`
=> fix: Fixing a type and making Judge user unique

packages/shared/src/schema/index.ts, packages/shared/src/schema/project/index.ts, packages/shared/src/schema/project/post.ts, packages/shared/tests/schema/project/post.test.ts, packages/shared/tests/schema/users/put.test.ts
- Adding project post schema
- Updating user put schema to use full import path instead of importing directly from the file itself
=> feat: Adding project schema

packages/api/tests/api/health/get.test.ts, packages/api/tests/api/project/post.test.ts, packages/api/tests/api/user/put.test.ts, packages/api/tests/middleware/adminMiddleware.test.ts, packages/api/tests/middleware/mountUserMiddleware.test.ts, packages/api/tests/testUtils/createMockEntityManager.ts, packages/api/tests/testUtils/expressHelpers/createMockRequest.ts, packages/api/tests/utils/authenticateUser.test.ts
- Cleaned up types related to the util
- Cleaned up tests to avoid using the util unless necessary
- Cleaned up types in other tests
=> feat: cleaning up createMockEntityManager util and related tests

packages/api/src/api/index.ts, packages/api/src/api/prize/get.ts, packages/api/src/api/prize/index.ts, packages/api/tests/api/prizes/get.test.ts, packages/api/tests/api/prizes/index.test.ts
=> feat: Prizes GET endpoint

packages/api/jest.config.js, packages/api/src/api/index.ts, packages/api/tests/api/admin/me/index.test.ts, packages/api/tests/api/index.test.ts, packages/database/jest.config.js, packages/shared/jest.config.js, packages/shared/src/types/entities/JudgingSession.ts, packages/shared/src/types/entities/Prize.ts, packages/shared/src/types/entities/index.ts
- Fixing a bad route for prizes
- Cleaning up tests
- Adding better test coverage for the core route handlers
- Cleaning up more shared entity types
=> feat: test cleanup and route fix

packages/api/src/api/expoJudgingSession/get.ts, packages/api/src/api/expoJudgingSession/index.ts, packages/api/tests/api/expoJudgingSession/get.test.ts, packages/api/tests/api/expoJudgingSession/index.test.ts
=> feat: GET expoJudgingSessions

packages/web/src/components/EventsList/EventsList.tsx, packages/web/src/components/Prizes/Prizes.tsx, packages/web/src/components/Prizes/PrizesList.tsx, packages/web/src/components/Prizes/index.tsx, packages/web/src/pages/index.tsx
=> feat: Prizes list UI

cspell.json, packages/api/src/api/auth/callback/slack/utils/localRedirect.ts, packages/api/src/middleware/adminMiddleware.ts, packages/api/src/middleware/mountUserMiddleware.ts, packages/api/tests/api/auth/callback/slack/utils/localRedirect.test.ts, packages/api/tests/api/project/post.test.ts, packages/api/tests/testUtils/mockEnv.test.ts, packages/database/src/entitiesUtils/scoreVotes.ts, packages/web/src/theme/components.ts
=> fix: Re-enabling spellcheck

packages/api/src/@types/index.d.ts, packages/api/src/middleware/judgeMiddleware.ts, packages/api/tests/middleware/adminMiddleware.test.ts, packages/api/tests/middleware/judgeMiddleware.test.ts
=> feat: Judge Middleware

packages/api/src/@types/index.d.ts, packages/api/src/api/auth/index.ts, packages/api/src/api/auth/logout/get.ts, packages/api/src/api/auth/logout/index.ts, packages/api/src/utils/authenticateUser.ts, packages/api/tests/api/auth/callback/slack/get.test.ts, packages/api/tests/api/auth/callback/slack/index.test.ts, packages/api/tests/api/auth/callback/slack/utils/localRedirect.test.ts, packages/api/tests/api/auth/get.test.ts, packages/api/tests/api/auth/logout/get.test.ts, packages/api/tests/api/auth/logout/index.test.ts, packages/api/tests/api/health/index.test.ts, packages/api/tests/api/slack/index.test.ts, packages/api/tests/api/user/put.test.ts, packages/api/tests/middleware/sessionMiddleware.test.ts, packages/api/tests/testUtils/expressHelpers/createMockRequest.ts, packages/api/tests/testUtils/expressHelpers/createMockResponse.ts, packages/api/tests/utils/authenticateUser.test.ts, packages/web/src/components/layout/AppLayout/NavBar/NavBar.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavDrawer.tsx, packages/web/src/stores/admin.ts
=> feat: adding logout and fixing admin store fetch

packages/web/src/components/layout/AppLayout/NavBar/NavBar.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavDrawer.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavElements/AuthButtons/Login.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavElements/AuthButtons/Logout.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavElements/AuthButtons/SignUp.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavElements/AuthButtons/utils.ts, packages/web/src/components/layout/AppLayout/NavBar/NavElements/PageLinks/AdminDashboard.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavElements/PageLinks/Schedule.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavLogo.tsx, packages/web/src/pages/schedule.tsx
Refactoring the nav with better usability
https://github.com/AmericanAirlines/Hangar/assets/6445731/7d0e4b51-6b15-4733-96fb-687f66715b03
https://github.com/AmericanAirlines/Hangar/assets/6445731/0105cec5-6180-4c6c-bc09-e4a74de80853
=> feat: nav refactor

packages/api/src/api/auth/callback/slack/get.ts, packages/api/src/api/auth/get.ts, packages/api/src/utils/authenticateUser.ts, packages/api/tests/api/auth/callback/slack/get.test.ts, packages/api/tests/api/auth/get.test.ts, packages/api/tests/utils/authenticateUser.test.ts, packages/shared/src/config/global.ts
=> feat: auth return url

packages/shared/src/schema/expoJudgingVote/index.ts, packages/shared/src/schema/expoJudgingVote/post.ts, packages/shared/src/schema/index.ts, packages/shared/tests/schema/expoJudgingVote/post.ts
=> feat: expo judging Vote Post Schema

packages/api/src/api/auth/callback/slack/get.ts, packages/api/src/api/auth/callback/slack/utils/localRedirect.ts, packages/api/src/api/auth/get.ts, packages/api/src/slack/formatSlackRedirectUri.ts, packages/api/tests/api/auth/callback/slack/get.test.ts, packages/api/tests/api/auth/callback/slack/utils/localRedirect.test.ts, packages/api/tests/api/auth/get.test.ts, packages/api/tests/slack/formatSlackRedirectUri.test.ts
=> fix: fixing auth flow

packages/api/src/api/expoJudgingSession/post.ts, packages/api/src/api/expoJudgingVote/post.ts, packages/api/src/api/judge/post.ts, packages/api/src/api/judge/put.ts, packages/api/tests/api/expoJudgingSession/post.test.ts, packages/api/tests/api/expoJudgingVote/post.test.ts, packages/api/tests/api/judge/post.test.ts, packages/api/tests/api/judge/put.test.ts, packages/database/src/entities/ExpoJudgingSessionContext.ts, packages/database/src/entities/ExpoJudgingVote.ts, packages/database/src/entities/Judge.ts, packages/database/src/entities/JudgingSession.ts, packages/database/src/entities/index.ts, packages/database/src/migrations/.snapshot-hangar.json, packages/database/src/migrations/0006-add-expojudgingsessioncontext-table.ts, packages/database/tests/entities/Judge.test.ts
=> feat: refactoring entities to support multi-session functionality

packages/database/src/migrations/0007-add-expojudgingsessioncontext-table.ts
=> fix: fixing migration order

packages/web/src/pages/index.tsx
=> fix: adding gates around display of the register button

packages/database/seeds/DatabaseSeeder.ts, packages/database/seeds/factories/ProjectFactory.ts, packages/database/seeds/seeders/ProjectSeeder.ts
=> feat: adding project entity to seeder

packages/web/src/components/ExpoJudging/ProjectCard/ProjectCard.tsx, packages/web/src/components/ExpoJudging/ProjectCard/index.ts, packages/web/src/components/ExpoJudging/ProjectCardsContainer/ProjectCardsContainer.tsx, packages/web/src/components/ExpoJudging/ProjectCardsContainer/index.ts, packages/web/src/components/ExpoJudging/hooks/useExpoJudging.ts, packages/web/src/components/ExpoJudging/index.ts, packages/web/src/pages/expoJudgingSession/[id]/index.tsx
Demo:
https://github.com/AmericanAirlines/Hangar/assets/6445731/dc16262e-6082-4c86-9f98-2c36c4971795
=> feat: adding UI components for Judging

packages/shared/tests/utils/wait.test.ts
=> fix: wait.ts test warnings

packages/database/src/entities/Prize.ts, packages/database/src/migrations/.snapshot-hangar.json, packages/database/src/migrations/0009-add-winner-to-prize.ts
=> feat: Prize entity modifications

packages/api/src/api/expoJudgingSession/id/continueSession/index.ts, packages/api/src/api/expoJudgingSession/id/projects/index.ts
=> fix: fixing two endpoints

packages/api/src/api/expoJudgingSession/id/continueSession/index.ts, packages/api/src/api/expoJudgingSession/id/continueSession/post.ts, packages/api/src/api/expoJudgingSession/id/projects/get.ts, packages/api/tests/api/expoJudgingSession/id/continueSession/index.test.ts, packages/api/tests/api/expoJudgingSession/id/continueSession/post.test.ts, packages/api/tests/api/expoJudgingSession/id/projects/get.test.ts, packages/database/src/entities/Judge.ts, packages/database/src/entities/Project.ts, packages/database/tests/entities/Judge.test.ts
=> fix: fixing issues related to judging

packages/api/src/api/project/id/get.ts, packages/api/src/api/project/id/index.ts, packages/api/src/api/project/index.ts, packages/api/tests/api/project/id/get.test.ts, packages/api/tests/api/project/id/index.test.ts
=> feat: Project get endpoint

packages/database/src/config/orm.config.ts
=> feat: enabling ssl in prod

packages/database/src/config/orm.config.ts
=> fix: ssl config

packages/api/src/api/criteriaJudgingSession/index.ts, packages/api/src/api/criteriaJudgingSession/post.ts, packages/api/src/api/index.ts, packages/api/tests/api/criteriaJudgingSession/index.test.ts, packages/api/tests/api/criteriaJudgingSession/post.test.ts, packages/database/src/entities/CriteriaJudgingSession.ts, packages/shared/src/schema/index.ts
=> feat: adding criteria judging session post endpoint

packages/shared/src/schema/criteria/criteria.ts, packages/web/src/components/Admin/CriteriaJudgingSessionForm/CriteriaJudgingSessionForm.tsx, packages/web/src/components/Admin/CriteriaJudgingSessionForm/CriteriaList/CriteriaFields.tsx, packages/web/src/components/Admin/CriteriaJudgingSessionForm/CriteriaList/CriteriaList.tsx, packages/web/src/components/Admin/CriteriaJudgingSessionForm/CriteriaList/index.ts, packages/web/src/components/Admin/CriteriaJudgingSessionForm/FormStyleContext.ts, packages/web/src/components/Admin/CriteriaJudgingSessionForm/index.ts, packages/web/src/components/Admin/CriteriaJudgingSessionForm/useCriteriaJudgingSessionForm.ts, packages/web/src/components/Admin/JudgingSessionList/JudgingSessionsOptionsButton/JudgingSessionOptionsButton.tsx, packages/web/src/components/Forms/FormHelperHint/FormHelperHint.tsx, packages/web/src/components/Forms/FormHelperHint/index.ts, packages/web/src/components/Forms/index.ts, packages/web/src/pages/admin/createCriteriaJudgingSession.tsx, packages/web/src/stores/criteriaJudgingSession/criteriaJudgingSession.ts
=> feat: adding create criteria judging session page

packages/api/src/api/criteriaJudgingSession/id/get.ts, packages/api/src/api/criteriaJudgingSession/id/index.ts, packages/api/src/api/criteriaJudgingSession/id/projects/get.ts, packages/api/src/api/criteriaJudgingSession/id/projects/index.ts, packages/api/src/middleware/criteriaJudgingSessionMiddleware.ts, packages/api/tests/api/criteriaJudgingSession/id/get.test.ts, packages/api/tests/api/criteriaJudgingSession/id/index.test.ts, packages/api/tests/api/criteriaJudgingSession/id/projects/get.test.ts, packages/api/tests/api/criteriaJudgingSession/id/projects/index.test.ts, packages/api/tests/middleware/criteriaJudgingSessionMiddleware.test.ts
=> feat: adding projects endpoint for criteria judging sessions

packages/web/src/components/CriteriaJudging/hooks/useCriteriaJudging/fetchProjects.ts, packages/web/src/components/CriteriaJudging/hooks/useCriteriaJudging/index.ts, packages/web/src/components/CriteriaJudging/hooks/useCriteriaJudging/useCriteriaJudging.ts, packages/web/src/pages/criteriaJudgingSession/[id]/index.tsx
- Fetching projects
- Displaying in a dropdown
=> feat: adding a project select to the criteria judging page

packages/api/src/api/criteriaJudgingSession/id/get.ts, packages/api/src/api/criteriaJudgingSubmission/post.ts, packages/api/tests/api/criteriaJudgingSession/id/get.test.ts, packages/shared/src/schema/criteriaScore/criteriaScore.ts, packages/shared/tests/schema/criteriaScore/criteriaScore.test.ts, packages/web/src/components/Admin/JudgingSessionList/JudgingSessionActionsMenu.tsx, packages/web/src/components/CriteriaJudging/CriteriaJudgingForm/CriteriaJudgingForm.tsx, packages/web/src/components/CriteriaJudging/CriteriaJudgingForm/ProjectDetails.tsx, packages/web/src/components/CriteriaJudging/CriteriaJudgingForm/index.ts, packages/web/src/components/CriteriaJudging/CriteriaJudgingForm/useCriteriaJudgingForm.ts, packages/web/src/components/CriteriaJudging/ProjectSelectionMenu/ProjectSelectionMenu.tsx, packages/web/src/components/CriteriaJudging/ProjectSelectionMenu/index.ts, packages/web/src/components/CriteriaJudging/hooks/index.ts, packages/web/src/components/CriteriaJudging/index.ts, packages/web/src/components/Forms/FormHelperHint/FormHelperHint.tsx, packages/web/src/components/layout/PageContainer/PageContainer.tsx, packages/web/src/pageUtils/judgingSession/useJudgingSessionFetcher.ts, packages/web/src/pages/criteriaJudgingSession/[id]/index.tsx
- Refactored CJS fetcher to make return type optional
- Added new components for judging flow
- Refactored CJS page with new components
=> feat: adding criteria judging session components

packages/api/src/api/criteriaJudgingSession/id/index.ts, packages/api/src/api/criteriaJudgingSession/id/results/get.ts, packages/api/src/api/criteriaJudgingSession/id/results/index.ts, packages/api/tests/api/criteriaJudgingSession/id/index.test.ts, packages/api/tests/api/criteriaJudgingSession/id/results/get.test.ts, packages/api/tests/api/criteriaJudgingSession/id/results/index.test.ts, packages/database/src/entities/Criteria.ts, packages/database/src/entities/CriteriaJudgingSubmission.ts, packages/database/src/migrations/.snapshot-hangar.json, packages/database/src/migrations/0013-changing-columntype-of-weight-to-decimal.ts, packages/shared/src/types/DTOs/CriteriaJudgingSessionResults.ts, packages/shared/src/types/DTOs/index.ts, packages/shared/src/types/entities/CriteriaJudgingSubmission.ts
=> feat: Adding CriteriaJudgingSession results endpoint

packages/database/seeds/seeders/UserSeeder.ts, packages/shared/src/types/DTOs/CriteriaJudgingSessionResults.ts, packages/web/src/components/Admin/CriteriaJudgingSessionProjectResults/CriteriaJudgingSessionProjectResults.tsx, packages/web/src/components/Admin/CriteriaJudgingSessionProjectResults/index.ts, packages/web/src/components/CriteriaJudging/CriteriaJudgingForm/ProjectDetails.tsx, packages/web/src/components/CriteriaJudging/ProjectSelectionMenu/ProjectSelectionMenu.tsx, packages/web/src/components/ExpoJudging/ExpoJudgingIntro/ExpoJudgingIntro.tsx, packages/web/src/pageUtils/admin/criteriaJudgingSession/[id]/fetchCriteriaJudgingSessionResults.ts, packages/web/src/pages/admin/criteriaJudgingSession/[id]/index.tsx
=> feat: criteria judging session results page

packages/web/src/components/EventsList/EventCard.tsx
=> feat: Schedule UI updates

Dockerfile
=> fix: fixing an issue where base url is not present at build time

packages/web/src/components/Prizes/PrizeCard.tsx, packages/web/src/components/ProjectCard/ProjectCard.tsx, packages/web/src/pages/project/[id]/index.tsx
=> feat:  Update Prize Card to Link to Winner

packages/shared/src/config/homepage.ts, packages/web/src/components/Prizes/Prizes.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavBar.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavDrawer.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavElements/PageLinks/Prizes.tsx, packages/web/src/pages/index.tsx
=> feat: adding prizes nav element and adding content sections to homepage

packages/shared/src/config/homepage.ts, packages/web/src/pages/index.tsx
=> feat: adding link customization to homepage content

packages/api/src/api/expoJudgingSession/id/results/get.ts, packages/api/tests/api/expoJudgingSession/id/results/get.test.ts, packages/database/src/entities/ExpoJudgingVote.ts, packages/web/src/pageUtils/expoJudgingSession/[id]/fetchExpoJudgingSessionResults.ts, packages/web/src/pages/admin/expoJudgingSession/[id]/index.tsx, packages/web/src/theme/components.ts
=> feat: fixing nav font weight, improving results error

package.json, packages/api/src/api/project/post.ts, packages/api/tests/api/project/post.test.ts, packages/web/src/components/ProjectRegistrationButton/useRegistrationConfig.tsx
=> fix: fixing an issue where project url fetch resulted in a timeout

packages/web/src/components/EventsList/EventCard.tsx, packages/web/src/components/EventsList/EventsList.tsx
Improving event card to automatically refresh status once every 60 seconds
=> feat: refactoring event card

packages/web/src/components/layout/AppLayout/NavBar/NavBar.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavDrawer.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavElements/PageLinks/MyProject.tsx
=>  feat: My project nav drawer and link

packages/database/seeds/factories/ProjectFactory.ts, packages/database/src/entities/Judge.ts, packages/database/src/entities/Project.ts, packages/database/src/entitiesUtils/Judge/getNextProject.ts, packages/database/tests/entities/ExpoJudgingVote.test.ts, packages/database/tests/entities/Judge.test.ts, packages/database/tests/entitiesUtils/Judge/getNextProject.test.ts, packages/web/src/components/ProjectRegistrationButton/utils.ts
=> feat: refactoring getNextProject

packages/api/src/api/project/get.ts, packages/api/src/api/project/index.ts, packages/api/tests/api/project/get.test.ts
=> feat: projects get endpoint

packages/database/src/migrations/.snapshot-hangar.json, packages/database/src/migrations/0014-drop-judge-count-column-from-project-table.ts
=> fix: dropping judgeVisits column

packages/web/src/components/ProjectsSelect/ProjectsSelect.tsx, packages/web/src/components/ProjectsSelect/ProjectsSelectActions.tsx, packages/web/src/components/ProjectsSelect/ProjectsSelectItem.tsx, packages/web/src/components/ProjectsSelect/ProjectsSelectStyleContext.ts, packages/web/src/components/ProjectsSelect/fetchProjects.ts, packages/web/src/components/ProjectsSelect/index.ts, packages/web/src/theme/colors.ts
=> feat: adding component for selecting projects

.github/workflows/build.yml, .github/workflows/quality.yaml, .github/workflows/tests.yaml, README.md, cspell.json, lerna.json, package.json, packages/api/package.json, packages/database/package.json, packages/database/src/entities/Judge.ts, packages/database/tests/entities/Judge.test.ts, packages/shared/package.json, packages/web/package.json, packages/web/src/components/layout/AppLayout/NavBar/NavBar.tsx, packages/web/src/components/layout/AppLayout/NavBar/NavLogo.tsx
- updating docs to prepare for v3
- updating version number
- fixing misc. tech debt
=> docs: V3 docs in preparation for updating main branch

packages/api/tests/api/project/post.test.ts
=> feat: improving test comments for clarity
